### PR TITLE
release 0.4.0

### PR DESCRIPTION
**Pull request by orbeckst**
- new dependency: tqdm
- new SHA256

Checklist
* [x] Used a fork of the feedstock to propose changes
* n/a Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by orbeckst** [comment]
@kain88-de @richardjgowers  I just released 0.5.0 https://github.com/MDAnalysis/MDAnalysisData/issues/31. I think we can merge this for 0.4.0 and then let 0.5.0 be rendered automagically (it's on PyPi and no dependencies changed).

**Comment by kain88-de** [comment]
I would like to wait for the new MDAnalysis release on conda forge. Then we
can set this package to noarch and have quicker builds.

**Comment by orbeckst** [comment]
Is this going to be live in time for the workshop?

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by richardjgowers** [comment]
Yeah these are fairly quick, I did mda proper this morning

**Pull request closed without merging**
